### PR TITLE
pullStream bug reproduction

### PR DESCRIPTION
**Pull request by LiamKrenn**
## This PR contains:
 - Bug reproduction unit test

## Describe the problem you have without this PR
All endpoints work - except the pullStream endpoint, which timeouts

@pubkey

### CODE REVIEW

**Comment by julikober** [comment]
Couldn't reproduce. It is working for me, please close some1.

**Comment by LiamKrenn** [comment]
Could you elaborate? It's a unit test

**Comment by julikober** [comment]
Oh I see someone is salty right now? Just becaus you can't run it? Then write a fix by yourself. It's just javascript at least

**Comment by JohnGrubba** [comment]
Wuduheeeeel

**Comment by LiamKrenn** [comment]
Thank you for your help @pubkey
[This solved my issue](https://www.triplit.dev/)

**Comment by LiamKrenn** [comment]
If someone else encounters this issue, [this fixed it](https://www.triplit.dev/)

**Comment by SchlexanderOlz** [comment]
I am also encountering this issue. Please fix

**Comment by julikober** [comment]
Thanks @LiamKrenn , really waited for this fix

**Comment by JohnGrubba** [comment]
Thanks @LiamKrenn! Solved it for me.

**Comment by HaiPaul** [comment]
Thanks @LiamKrenn! Love the quick fix. Really needed this!

**Pull request closed without merging**
